# This is a basic workflow to help you get started with Actions

name: 'self hosted runner demo'

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello-self-hosted-runner:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64, ubuntu]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: run-me-inside-self-hosted-runner
      run: echo "Howdy github actions. I know I am getting executed on a self hosted runner"

    - name: sleep for 100 seconds
      run: sleep 100

    - name: get os version
      run: cat /etc/os-release
      
